### ISSUE TITLE
Wrong binary

### ISSUE THREAD

**Issue by murmelbahn** [hotcereal/cloud-saves-miyoo-mini-plus#1]
Thanks for this great app @hotcereal !
One little thing: 
The linked rclone binary in the readme file is wrong. You need the [ARM v7 32-bit](https://downloads.rclone.org/v1.62.2/rclone-v1.62.2-linux-arm-v7.zip)

**Comment by Hollyrious** [comment]
Use [ARM v6 64-bit](https://downloads.rclone.org/v1.64.0/rclone-v1.64.0-linux-arm-v6.zip) instead as I mentioned in #1.

**Comment by othyn** [comment]
Latest ARM v7 binary also works

https://downloads.rclone.org/v1.64.2/rclone-v1.64.2-linux-arm-v7.zip

```sh
/mnt/SDCARD # uname -a
Linux (none) 4.9.84 #1136 SMP PREEMPT Wed Jun 28 21:28:40 HKT 2023 armv7l GNU/Linux

/mnt/SDCARD # ./rclone version
rclone v1.64.2
- os/version: unknown
- os/kernel: 4.9.84 (armv7l)
- os/type: linux
- os/arch: arm (ARMv7 compatible)
- go/version: go1.21.3
- go/linking: static
- go/tags: none
```
