### ISSUE TITLE
ERROR : Failed to save config after 10 tries: failed to create temp file for new config: open /.rclone.conf2872691618: read-only file system

### ISSUE THREAD

**Issue by edmunek** [hotcereal/cloud-saves-miyoo-mini-plus#3]
Attempting to configure the rclone always ends with an error that it is unable to create a temp file for the config file
This occurs with the v1.65.0 arm7 rclone bin file placed in the root of the SDCARD
same occurs on the suggested (by OP) version 1.62.2

<img width="976" alt="231207_124356 - dlsFAlh2UF" src="https://github.com/hotcereal/cloud-saves-miyoo-mini-plus/assets/10533120/1081c796-089d-4218-a8a8-654247e9d3ad">

**Comment by zilberd** [comment]
just create an empty rcloud.conf file at the root odf the sdcard and it should work

**Comment by nicktheone** [comment]
To add (and correct the typo as it isn't r**cloud** but r**clone** on what @zilberd said, SSH into your MiYoo and do

`touch /mnt/SDCARD/rclone.conf`

This will create the file rclone needs.
