### ISSUE TITLE
Failed to create file system for "cloud:Onion/saves/retroarch/": didn't find section in config file

### ISSUE THREAD

**Issue by edmunek** [hotcereal/cloud-saves-miyoo-mini-plus#4]
No matter of which option would be used for the rclone connection, the launch script ends with an error:

Failed to create file system for "cloud:Onion/saves/retroarch/": didn't find section in config file

<img width="745" alt="231207_131711 - dmGYU7nT4W" src="https://github.com/hotcereal/cloud-saves-miyoo-mini-plus/assets/10533120/cc9ba191-5019-4eee-b2ab-aa31668acf18">

**Comment by nicktheone** [comment]
Did you name your share "cloud"? Please post the content of the `rclone.conf` file.

**Comment by hotcereal** [comment]
Response above is correct. The error you're receiving is because the `rclone.conf` cannot find a share named `cloud`.

Sorry for the late response. I have failed you.
